parameters:
    database_driver:   pdo_pgsql
    database_host:     127.0.0.1
    database_port:     5432
    database_name:     tndw_web
    database_user:     postgres
    database_password: root

    database_driver_trol:   pdo_pgsql
    database_host_trol:     127.0.0.1
    database_port_trol:     5432
    database_name_trol:     troller
    database_user_trol:     postgres
    database_password_trol: root

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    facebookAppId:  529361697103665
    facebookAppSecret:  6af6d1bb809129482d799e61e970e492
