parameters:
#    tn_dw_web.example.class: TnDW\WebBundle\Example

services:
#    tn_dw_web.example:
#        class: %tn_dw_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
